insert into public.la_schools (id, name, type, address, atpt_code, school_code, lat, lng, created_at)
select id, name, type, address, atpt_code, school_code, lat, lng, coalesce(created_at, now())
from public.schools
on conflict (id) do update
set name = excluded.name,
    type = excluded.type,
    address = excluded.address,
    atpt_code = excluded.atpt_code,
    school_code = excluded.school_code,
    lat = excluded.lat,
    lng = excluded.lng;

create table if not exists public.la_meals (
  id bigint generated by default as identity primary key,
  school_id bigint references public.la_schools(id) on delete cascade,
  meal_date date not null,
  menu jsonb not null,
  calories real,
  nutrition text,
  auto_score integer,
  auto_rank text,
  created_at timestamptz default now(),
  meal_type text not null default 'lunch',
  meal_type_label text not null default '중식',
  neis_meal_code text,
  constraint la_meals_meal_type_check check (meal_type in ('breakfast','lunch','dinner','snack','other')),
  constraint la_meals_school_date_type_key unique (school_id, meal_date, meal_type)
);

create index if not exists la_meals_school_date_idx on public.la_meals(school_id, meal_date);
create index if not exists la_meals_date_score_idx on public.la_meals(meal_date, auto_score desc);

create table if not exists public.la_reviews (
  id bigint generated by default as identity primary key,
  meal_id bigint references public.la_meals(id) on delete cascade,
  school_id bigint references public.la_schools(id) on delete cascade,
  score integer not null check (score between 1 and 5),
  comment text check (comment is null or char_length(comment) <= 100),
  user_key text,
  created_at timestamptz default now(),
  photo_url text,
  nickname text check (nickname is null or char_length(nickname) between 2 and 12),
  selected_menu_item text,
  meal_date_snapshot date,
  meal_type_snapshot text,
  meal_menu_snapshot jsonb,
  constraint la_reviews_meal_user_key unique (meal_id, user_key)
);

create index if not exists la_reviews_school_created_idx on public.la_reviews(school_id, created_at desc);
create index if not exists la_reviews_meal_created_idx on public.la_reviews(meal_id, created_at desc);
create index if not exists la_reviews_user_key_idx on public.la_reviews(user_key);

create table if not exists public.la_review_comments (
  id bigint generated by default as identity primary key,
  rating_id bigint not null references public.la_reviews(id) on delete cascade,
  user_key text not null,
  nickname text,
  comment text not null check (char_length(comment) between 1 and 300),
  created_at timestamptz default now()
);

create index if not exists la_review_comments_rating_created_idx on public.la_review_comments(rating_id, created_at);

create table if not exists public.la_review_reactions (
  id bigint generated by default as identity primary key,
  rating_id bigint not null references public.la_reviews(id) on delete cascade,
  user_key text not null,
  nickname text,
  reaction text not null check (reaction in ('like','dislike')),
  created_at timestamptz default now(),
  cancel_token_hash text check (cancel_token_hash is null or char_length(cancel_token_hash) between 32 and 128),
  constraint la_review_reactions_rating_user_key unique (rating_id, user_key)
);

create index if not exists la_review_reactions_rating_idx on public.la_review_reactions(rating_id);

create table if not exists public.la_battles (
  id bigint generated by default as identity primary key,
  battle_date date not null,
  school_a_id bigint references public.la_schools(id) on delete cascade,
  school_b_id bigint references public.la_schools(id) on delete cascade,
  meal_a_id bigint references public.la_meals(id) on delete set null,
  meal_b_id bigint references public.la_meals(id) on delete set null,
  score_a integer default 0,
  score_b integer default 0,
  vote_a integer default 0,
  vote_b integer default 0,
  winner_id bigint references public.la_schools(id) on delete set null,
  status text default 'active',
  created_at timestamptz default now(),
  constraint la_battles_date_pair_key unique (battle_date, school_a_id, school_b_id)
);

create index if not exists la_battles_date_school_a_idx on public.la_battles(battle_date, school_a_id);
create index if not exists la_battles_date_school_b_idx on public.la_battles(battle_date, school_b_id);

create table if not exists public.la_battle_votes (
  id bigint generated by default as identity primary key,
  battle_id bigint references public.la_battles(id) on delete cascade,
  voted_school_id bigint references public.la_schools(id) on delete cascade,
  user_key text not null,
  created_at timestamptz default now(),
  constraint la_battle_votes_battle_user_key unique (battle_id, user_key)
);

create index if not exists la_battle_votes_battle_idx on public.la_battle_votes(battle_id);

alter table public.la_review_photos
  add column if not exists review_id bigint;

alter table public.la_review_photos
  alter column rating_id drop not null;

alter table public.la_review_photos
  drop constraint if exists la_review_photos_rating_id_fkey,
  drop constraint if exists review_photos_rating_id_fkey,
  drop constraint if exists la_review_photos_meal_id_fkey;

alter table public.la_review_photos
  drop constraint if exists la_review_photos_review_id_fkey,
  drop constraint if exists la_review_photos_meal_id_fkey,
  drop constraint if exists la_review_photos_rating_id_fkey,
  drop constraint if exists review_photos_rating_id_fkey;

alter table public.la_review_photos
  add constraint la_review_photos_review_id_fkey
  foreign key (review_id) references public.la_reviews(id) on delete cascade;

alter table public.la_review_photos
  add constraint la_review_photos_meal_id_fkey
  foreign key (meal_id) references public.la_meals(id) on delete set null;

alter table public.la_activity_events
  drop constraint if exists la_activity_events_meal_id_fkey,
  drop constraint if exists la_activity_events_rating_id_fkey;

alter table public.la_activity_events
  add constraint la_activity_events_meal_id_fkey
  foreign key (meal_id) references public.la_meals(id) on delete set null not valid;

alter table public.la_activity_events
  add constraint la_activity_events_rating_id_fkey
  foreign key (rating_id) references public.la_reviews(id) on delete set null not valid;

alter table public.la_meals enable row level security;
alter table public.la_reviews enable row level security;
alter table public.la_review_comments enable row level security;
alter table public.la_review_reactions enable row level security;
alter table public.la_battles enable row level security;
alter table public.la_battle_votes enable row level security;

drop policy if exists "Public read la meals" on public.la_meals;
create policy "Public read la meals" on public.la_meals for select to anon, authenticated using (true);

drop policy if exists "Public read la reviews" on public.la_reviews;
create policy "Public read la reviews" on public.la_reviews for select to anon, authenticated using (true);

drop policy if exists "Public insert la reviews" on public.la_reviews;
create policy "Public insert la reviews" on public.la_reviews for insert to anon, authenticated with check (true);

drop policy if exists "Owner update la reviews" on public.la_reviews;
create policy "Owner update la reviews" on public.la_reviews for update to anon, authenticated using (user_key = current_setting('request.headers', true)::json->>'x-review-owner-key') with check (user_key = current_setting('request.headers', true)::json->>'x-review-owner-key');

drop policy if exists "Owner delete la reviews" on public.la_reviews;
create policy "Owner delete la reviews" on public.la_reviews for delete to anon, authenticated using (user_key = current_setting('request.headers', true)::json->>'x-review-owner-key');

drop policy if exists "Public read la review comments" on public.la_review_comments;
create policy "Public read la review comments" on public.la_review_comments for select to anon, authenticated using (true);

drop policy if exists "Public insert la review comments" on public.la_review_comments;
create policy "Public insert la review comments" on public.la_review_comments for insert to anon, authenticated with check (true);

drop policy if exists "Public read la review reactions" on public.la_review_reactions;
create policy "Public read la review reactions" on public.la_review_reactions for select to anon, authenticated using (true);

drop policy if exists "Public insert la review reactions" on public.la_review_reactions;
create policy "Public insert la review reactions" on public.la_review_reactions for insert to anon, authenticated with check (true);

drop policy if exists "Token delete la review reactions" on public.la_review_reactions;
create policy "Token delete la review reactions" on public.la_review_reactions for delete to anon, authenticated using (cancel_token_hash = current_setting('request.headers', true)::json->>'x-reaction-cancel-token-hash');

drop policy if exists "Public read la battles" on public.la_battles;
create policy "Public read la battles" on public.la_battles for select to anon, authenticated using (true);

drop policy if exists "Public insert la battles" on public.la_battles;
create policy "Public insert la battles" on public.la_battles for insert to anon, authenticated with check (true);

drop policy if exists "Public update la battles" on public.la_battles;
create policy "Public update la battles" on public.la_battles for update to anon, authenticated using (true) with check (true);

drop policy if exists "Public delete la battles" on public.la_battles;
create policy "Public delete la battles" on public.la_battles for delete to anon, authenticated using (true);

drop policy if exists "Public read la battle votes" on public.la_battle_votes;
create policy "Public read la battle votes" on public.la_battle_votes for select to anon, authenticated using (true);

drop policy if exists "Public insert la battle votes" on public.la_battle_votes;
create policy "Public insert la battle votes" on public.la_battle_votes for insert to anon, authenticated with check (true);

grant select on public.la_meals to anon, authenticated;
grant select, insert, update, delete on public.la_reviews to anon, authenticated;
grant select, insert on public.la_review_comments to anon, authenticated;
grant select, insert, delete on public.la_review_reactions to anon, authenticated;
grant select, insert, update, delete on public.la_battles to anon, authenticated;
grant select, insert on public.la_battle_votes to anon, authenticated;

grant usage, select on sequence public.la_meals_id_seq to anon, authenticated;
grant usage, select on sequence public.la_reviews_id_seq to anon, authenticated;
grant usage, select on sequence public.la_review_comments_id_seq to anon, authenticated;
grant usage, select on sequence public.la_review_reactions_id_seq to anon, authenticated;
grant usage, select on sequence public.la_battles_id_seq to anon, authenticated;
grant usage, select on sequence public.la_battle_votes_id_seq to anon, authenticated;

create or replace view public.la_school_engagement_monthly
with (security_invoker = true) as
select
  date_trunc('month', r.created_at)::date as month,
  r.school_id,
  count(distinct r.id)::integer as review_count,
  count(distinct c.id)::integer as comment_count,
  count(distinct rr.id)::integer as reaction_count,
  count(distinct p.id)::integer as photo_count,
  (
    count(distinct r.id) * 10
    + count(distinct c.id) * 3
    + count(distinct rr.id)
    + count(distinct p.id) * 5
  )::numeric as score
from public.la_reviews r
left join public.la_review_comments c on c.rating_id = r.id
left join public.la_review_reactions rr on rr.rating_id = r.id
left join public.la_review_photos p on p.review_id = r.id and p.deleted_at is null
group by 1, r.school_id;

create or replace view public.la_school_menu_stats_monthly
with (security_invoker = true) as
select
  date_trunc('month', r.created_at)::date as month,
  r.school_id,
  r.selected_menu_item as menu_item,
  count(*)::integer as pick_count,
  avg(r.score)::numeric as avg_score,
  count(p.id)::integer as photo_count
from public.la_reviews r
left join public.la_review_photos p on p.review_id = r.id and p.deleted_at is null
where r.selected_menu_item is not null and btrim(r.selected_menu_item) <> ''
group by 1, r.school_id, r.selected_menu_item;

create or replace function public.la_find_battle_opponents(
  p_my_lat double precision,
  p_my_lng double precision,
  p_my_type text,
  p_my_id bigint,
  p_date date,
  p_limit integer default 20
)
returns table (
  school_id bigint,
  school_name text,
  school_type text,
  address text,
  atpt_code text,
  school_code text,
  meal_id bigint,
  auto_score integer,
  auto_rank text,
  menu jsonb,
  distance_km double precision
)
language sql
stable
as $$
  select
    s.id,
    s.name,
    s.type,
    s.address,
    s.atpt_code,
    s.school_code,
    m.id,
    m.auto_score,
    m.auto_rank,
    m.menu,
    (
      6371 * acos(
        least(1, greatest(-1,
          cos(radians(p_my_lat)) * cos(radians(s.lat::double precision))
          * cos(radians(s.lng::double precision) - radians(p_my_lng))
          + sin(radians(p_my_lat)) * sin(radians(s.lat::double precision))
        ))
      )
    )::double precision as distance_km
  from public.la_schools s
  join public.la_meals m on m.school_id = s.id and m.meal_date = p_date
  where s.id <> p_my_id
    and s.lat is not null
    and s.lng is not null
    and (p_my_type is null or p_my_type = '' or s.type ilike '%' || p_my_type || '%')
  order by distance_km asc, m.auto_score desc nulls last
  limit least(greatest(coalesce(p_limit, 20), 1), 100);
$$;

grant select on public.la_school_engagement_monthly to anon, authenticated;
grant select on public.la_school_menu_stats_monthly to anon, authenticated;
grant execute on function public.la_find_battle_opponents(double precision,double precision,text,bigint,date,integer) to anon, authenticated;
