create table if not exists public.la_schools (
  id bigint generated by default as identity primary key,
  atpt_code text not null,
  school_code text not null,
  name text not null,
  type text,
  address text,
  lat double precision,
  lng double precision,
  total_rating_score bigint default 0,
  rating_count bigint default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (atpt_code, school_code)
);

insert into public.la_schools (
  id,
  atpt_code,
  school_code,
  name,
  type,
  address,
  lat,
  lng,
  total_rating_score,
  rating_count,
  metadata,
  created_at,
  updated_at
)
select
  id,
  atpt_code,
  school_code,
  name,
  type,
  address,
  lat,
  lng,
  coalesce(total_rating_score, 0),
  coalesce(rating_count, 0),
  jsonb_build_object('migrated_from', 'schools'),
  created_at,
  now()
from public.schools
on conflict (id) do update
set atpt_code = excluded.atpt_code,
    school_code = excluded.school_code,
    name = excluded.name,
    type = excluded.type,
    address = excluded.address,
    lat = excluded.lat,
    lng = excluded.lng,
    total_rating_score = excluded.total_rating_score,
    rating_count = excluded.rating_count,
    updated_at = now();

select setval(
  pg_get_serial_sequence('public.la_schools', 'id'),
  greatest((select coalesce(max(id), 1) from public.la_schools), 1),
  true
);

create index if not exists idx_la_schools_name on public.la_schools(name);
create index if not exists idx_la_schools_location on public.la_schools(lat, lng);
create index if not exists idx_la_schools_type on public.la_schools(type);

alter table public.la_schools enable row level security;

revoke all on public.la_schools from anon, authenticated;
grant select on public.la_schools to anon, authenticated;

drop policy if exists la_schools_public_read on public.la_schools;
create policy la_schools_public_read
  on public.la_schools
  for select
  to anon, authenticated
  using (true);

alter table public.la_activity_events
  drop constraint if exists la_activity_events_school_id_fkey,
  add constraint la_activity_events_school_id_fkey
    foreign key (school_id) references public.la_schools(id) on delete set null;

alter table public.la_community_comments
  drop constraint if exists la_community_comments_school_id_fkey,
  add constraint la_community_comments_school_id_fkey
    foreign key (school_id) references public.la_schools(id) on delete cascade;

alter table public.la_community_posts
  drop constraint if exists la_community_posts_school_id_fkey,
  add constraint la_community_posts_school_id_fkey
    foreign key (school_id) references public.la_schools(id) on delete cascade;

alter table public.la_community_reactions
  drop constraint if exists la_community_reactions_school_id_fkey,
  add constraint la_community_reactions_school_id_fkey
    foreign key (school_id) references public.la_schools(id) on delete set null;

alter table public.la_feed_items
  drop constraint if exists la_feed_items_school_id_fkey,
  add constraint la_feed_items_school_id_fkey
    foreign key (school_id) references public.la_schools(id) on delete set null;

alter table public.la_leaderboard_snapshots
  drop constraint if exists la_leaderboard_snapshots_school_id_fkey,
  add constraint la_leaderboard_snapshots_school_id_fkey
    foreign key (school_id) references public.la_schools(id) on delete cascade;

alter table public.la_mission_school_targets
  drop constraint if exists la_mission_school_targets_school_id_fkey,
  add constraint la_mission_school_targets_school_id_fkey
    foreign key (school_id) references public.la_schools(id) on delete cascade;

alter table public.la_moderation_reports
  drop constraint if exists la_moderation_reports_school_id_fkey,
  add constraint la_moderation_reports_school_id_fkey
    foreign key (school_id) references public.la_schools(id) on delete set null;

alter table public.la_review_photos
  drop constraint if exists la_review_photos_school_id_fkey,
  add constraint la_review_photos_school_id_fkey
    foreign key (school_id) references public.la_schools(id) on delete set null;

alter table public.la_school_daily_metrics
  drop constraint if exists la_school_daily_metrics_school_id_fkey,
  add constraint la_school_daily_metrics_school_id_fkey
    foreign key (school_id) references public.la_schools(id) on delete cascade;

alter table public.la_user_mission_progress
  drop constraint if exists la_user_mission_progress_school_id_fkey,
  add constraint la_user_mission_progress_school_id_fkey
    foreign key (school_id) references public.la_schools(id) on delete set null;

alter table public.la_user_point_ledger
  drop constraint if exists la_user_point_ledger_school_id_fkey,
  add constraint la_user_point_ledger_school_id_fkey
    foreign key (school_id) references public.la_schools(id) on delete set null;

alter table public.la_user_profiles
  drop constraint if exists la_user_profiles_selected_school_id_fkey,
  add constraint la_user_profiles_selected_school_id_fkey
    foreign key (selected_school_id) references public.la_schools(id) on delete set null;

alter table public.la_user_school_memberships
  drop constraint if exists la_user_school_memberships_school_id_fkey,
  add constraint la_user_school_memberships_school_id_fkey
    foreign key (school_id) references public.la_schools(id) on delete cascade;

comment on table public.la_schools is 'LA-owned school master copied from legacy schools and used by la_* domain tables.';
